routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('home');
//});

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('/news', 'NewsController');

Route::get('/news/category/{categoryName}', 'NewsController@indexWithCategory')->name('listByCat');

Route::get('/dedicated-news', 'NewsController@indexDedicated')->name('news.dedicated');

Route::resource('/categories', 'CategoriesController');

Route::prefix('comments')->group(function () {

    Route::post('/', 'CommentsController@store')->name('comments.store');

    Route::get('/{id}', 'CommentsController@approve')->name('comments.approve');
});

Route::get('instagram', 'InstagramController@show');

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                        <div class="btn-group" role="group" aria-label="Blog Management">
                            <a href="{{ route('news.create') }}" class="btn btn-primary">Create News</a>
                            <a href="{{ route('categories.index') }}" class="btn btn-primary">Category</a>

                        </div>
                    <hr>
                    <hr>
                    <p class="text-center">All News</p>
                    @foreach($news as $singleNews)
                        <div class="row">
                            <div class="col-sm-3">
                                <img class="img-responsive" src="{{ asset('/storage/news-images') }}/{{ $singleNews->image }}">
                            </div>
                            <div class="col-sm-9">
                                <h3>{{ $singleNews->title }}</h3>
                                <p>{{ $singleNews->excerpt }}</p>
                            </div>
                            <div class="pull-right">
                                <a href="{{ route('news.edit', [ 'id' => $singleNews->id ] ) }}" class="btn btn-primary">Edit</a>
                                <form method="post" action="{{ route('news.destroy', [ 'id' => $singleNews->id ] ) }}" style="display:inline-block">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="delete">
                                    <input type="submit" class="btn btn-danger" value="delete">
                                </form>
                            </div>
                        </div>
                        <hr>
                    @endforeach
                    {{ $news->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1 class="text text-center">BBC</h1>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <h3 class="text-center">Categories</h3>
                @if( count( $categories ) > 0 )
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{{ route('news.index') }}">All news</a></li>
                        @foreach( $categories as $category )
                            <li class="list-group-item"><a href="{{ route('listByCat', [ 'categoryName' => $category->title ] ) }}">{{ $category->title }}</a></li>
                            @if( $category->has('subcategories') )
                                <ul>
                                    @foreach( $category->subcategories as $subcategory )
                                        <li class="list-group-item"><a href="{{ route('listByCat', [ 'categoryName' => $subcategory->title ] ) }}">{{ $subcategory->title }}</a></li>
                                    @endforeach
                                </ul>
                            @endif
                        @endforeach
                    </ul>
                @endif
            </div>
            <div class="col-sm-4" style="border:solid black;">
            right panel
                <br><br>

            </div>

        </div>
    </div>
@endsection

resources/views/instagram.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1 class="text text-center">BBC</h1>
        </div>
        <div class="row">
            @foreach( $instaData as $singleData )
                <div class="col-sm-4" style="border:solid #000">
                    <h3><strong>{{ $singleData->caption->text }}</strong></h3>
                    <a href="{{ $singleData->link }}">
                        <img width="{{ $singleData->images->thumbnail->width }}" height="{{ $singleData->images->thumbnail->height }}"
                             class="img-responsive img-rounded" src="{{ $singleData->images->thumbnail->url }}" alt="">
                    </a>
                </div>
            @endforeach
        </div>
    </div>
@endsection