routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('home');
//});

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('/news', 'NewsController');

Route::get('/news/category/{categoryName}', 'NewsController@indexWithCategory')->name('listByCat');

Route::get('/dedicated-news', 'NewsController@indexDedicated')->name('news.dedicated');

Route::resource('/categories', 'CategoriesController');

Route::prefix('comments')->group(function () {

    Route::post('/', 'CommentsController@store')->name('comments.store');

    Route::get('/{id}', 'CommentsController@approve')->name('comments.approve');
});

Route::get('instagram', 'InstagramController@show');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function categories()
    {
        return $this->belongsToMany('App\Category', 'categories_news' );
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\News;
use App\Category;
use App\Http\Requests\StoreNews;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class NewsController extends Controller
{
    /**
     * NewsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', [ 'except' => ['index', 'show', 'indexWithCategory', 'indexDedicated'] ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if( auth()->check() ) {
            $news = News::orderBy('created_at', 'desc')->paginate(5);
        } else {
            $news = News::orderBy('created_at', 'desc')->where('is_active', 1)->paginate(5);
        }

        return view('news.index')->with( 'news', $news );
    }

    /**
     * Show all news that belongs to this category
     * @param Category Name $category
     * @return view
     */
    public function indexWithCategory($category)
    {
        $currentCollCat = Category::where('title', $category)->first();
        $currentCat = Category::find($currentCollCat->id);
        $subcategories = $currentCat->subcategories;
        $subcategoriesTitle = $this->getSubcategoriesTitle($subcategories);

        $news = News::whereHas('categories', function($query) use ($category, $subcategoriesTitle) {
            $query->where('title', $category)->orWhereIn('title', $subcategoriesTitle);
        })->paginate(5);

        return view('news.index')->with('news', $news);
    }

    /**
     * extract all subcategories title from a subcategories object
     * @param $subcategories
     * @return array subcategories title
     */
    public function getSubcategoriesTitle($subcategories)
    {
        $titles = array();
        foreach ($subcategories as $subcategory){
            array_push($titles, $subcategory->title);
        }
        return $titles;
    }
    /**
     * Show all news that are dedicated
     * @return view
     */
    public function  indexDedicated()
    {
        $news = News::where('kind', 'ویژه')->paginate(5);

        return view('news.index')->with('news', $news);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('news.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreNews  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreNews $request)
    {
        $news = new News();

        $news->title = $request->input('title');
        $news->body = $request->input('body');
        $news->excerpt = $request->input('excerpt');
        $news->type = $request->input('type');
        $news->kind = $request->input('kind');
        $news->is_active = $request->input('is_active') ? 1 : 0;
        $categories = $request->input('categories');

        $image = $request->file('image');
        if( $image != null ) {
           $imagePath = $request->file('image')->store('public/news-images');
           $imageName = basename($imagePath);
           $news->image = $imageName;
        } else {
            $news->image = "bbc_news_logo.png";
        }

        DB::transaction(function () use ($news, $categories) {
            $news->save();
            $news->categories()->attach( $categories );
        });

        return redirect()->route('dashboard')->with('success', 'News has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $news = News::find($id);

        if( auth()->check() ) {
            $comments = $news->comments;
        } else {
            $comments = $news->comments()->where('is_active', 1)->get();
        }

        return view( 'news.show' )->with( [ 'news' => $news, 'comments' => $comments ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::find($id);
        $categories = Category::all();
        $categoriesId = $this->getCategoriesId( $news->categories );

        return view('news.edit')->with( [ 'news' => $news, 'categories' => $categories,
            'newsCategoriesId' => $categoriesId ] );
    }

    public function getCategoriesId($categories)
    {
        $allCatId = array();
        foreach ($categories as $category) {
            array_push( $allCatId, $category->id);
        }
        return $allCatId;
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreNews $request, $id)
    {
        $news = News::find($id);

        $news->title = $request->input('title');
        $news->body = $request->input('body');
        $news->excerpt = $request->input('excerpt');
        $news->type = $request->input('type');
        $news->kind = $request->input('kind');
        $news->is_active = $request->input('state') ? 1 : 0;
        $categories = $request->input('categories');

        $image = $request->file('image');
        if( $image != null ) {
            $imagePath = $request->file('image')->store('public/news-images');
            $imageName = basename($imagePath);
            Storage::delete('public/news-images/' . $news->image);
            $news->image = $imageName;
        }

        DB::transaction(function () use($news, $categories) {
            $news->save();

            $news->categories()->detach( Category::all('id') );

            $news->categories()->attach( $categories );
        });

        return redirect()->route('dashboard')->with('success', 'News has been Updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::find($id);

        if( $news->delete() ) {
            Storage::delete('public/news-images/' . $news->image);

            return redirect()->route('dashboard' )->with('success', 'news has been deleted.');
        }
    }
}

resources/views/news/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create news</div>

                    <div class="panel-body">
                        <form method="post" action="{{ route('news.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" value="{{ old('title') }}" id="title" name="title" >
                            </div>
                            <div class="form-group">
                                <label for="body">News body</label>
                                <textarea rows="10" class="form-control" id="body" name="body">{{ old('body') }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="excerpt">Excerpt</label>
                                <textarea rows="3" class="form-control" id="excerpt" name="excerpt">{{ old('excerpt') }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="type">Type</label>

                                <select name="type" id="type" class="form-control">
                                    <option {{ old('type') == 'آموزشی' ? 'selected' : '' }}>آموزشی</option>
                                    <option {{ old('type') == 'اجتماعی' ? 'selected' : '' }}>اجتماعی</option>
                                    <option {{ old('type') == 'فرهنگی' ? 'selected' : '' }}>فرهنگی</option>
                                    <option {{ old('type') == 'ورزشی' ? 'selected' : '' }}>ورزشی</option>
                                </select>
                            </div>
                            <div style="border: 1px solid #6f6">
                                <strong>kind</strong>
                                <div class="form-group">
                                    <label for="kind">Dedicated</label>
                                    <input type="radio" value="ویژه" name="kind" {{ old('kind') == 'ویژه' ? 'checked' : '' }} >
                                </div>
                                <div class="form-group">
                                    <label for="kind">No Dedicated</label>
                                    <input type="radio" value="عادی" name="kind" {{ ( old('kind') == 'عادی' or old('kind') == null ) ? 'checked' : '' }} >
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="image">Image</label>
                                <input type="file" class="form-control" id="image" name="image" >
                            </div>
                            <div class="form-group">
                                <label for="is_active">Active</label>
                                <input type="checkbox" {{ old('is_active') == "on" ? 'checked' : '' }} id="is_active" name="is_active"  data-toggle="toggle" data-onstyle="primary">
                            </div>
                            <div class="form-group">
                                @foreach( $categories as $category )
                                    <label for="categories">{{ $category->title }}</label>
                                    <input type="checkbox" name="categories[{{ $category->id }}]" value="{{ $category->id }}"  data-toggle="toggle" data-onstyle="primary"
                                           @if(array_key_exists($category->id, old('categories', []))) checked @endif >
                                @endforeach
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create news</div>

                    <div class="panel-body">
                        <form method="post" action="{{ route('news.update', [ 'id' => $news->id ] ) }}" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put">
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" class="form-control" id="title" name="title" value="{{ $news->title }}" >
                            </div>
                            <div class="form-group">
                                <label for="body">News body</label>
                                <textarea rows="10" class="form-control" id="body" name="body">{{ $news->body }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="excerpt">Excerpt</label>
                                <textarea rows="3" class="form-control" id="excerpt" name="excerpt">{{ $news->excerpt }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="type">Type</label>
                                <select name="type" id="type" class="form-control">
                                    <option {{ $news->type == 'آموزشی' ? 'selected' : '' }}>آموزشی</option>
                                    <option {{ $news->type == 'اجتماعی' ? 'selected' : '' }}>اجتماعی</option>
                                    <option {{ $news->type == 'فرهنگی' ? 'selected' : '' }}>فرهنگی</option>
                                    <option {{ $news->type == 'ورزشی' ? 'selected' : '' }}>ورزشی</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="kind">Dedicated</label>
                                <input type="radio" value="ویژه" name="kind" {{ $news->kind == 'ویژه' ? 'checked' : '' }} >
                            </div>
                            <div class="form-group">
                                <label for="kind">No Dedicated</label>
                                <input type="radio" value="عادی" name="kind" {{ $news->kind != 'ویژه' ? 'checked' : '' }} >
                            </div>
                            <div class="form-group" style="border: 1px solid #6f6;">
                                <div>
                                    <label for="imageInput">Image</label>
                                    <img id="newsImage" src="{{ asset('/storage/news-images') }}/{{ $news->image }}" class="img-responsive" width="200" height="180">
                                </div>
                                <input type="file" class="form-control" id="imageInput" name="image" >
                            </div>
                            <div class="form-group">
                                <label for="state">Active</label>
                                <input type="checkbox" id="state" name="state" data-toggle="toggle" data-onstyle="primary"
                                        {{ $news->is_active ? 'checked' : '' }}>
                            </div>

                            <div class="form-group">
                                @foreach( $categories as $category )
                                    <label for="categories">{{ $category->title }}</label>
                                    <input type="checkbox" name="categories[]" value="{{ $category->id }}"  data-toggle="toggle"
                                           data-onstyle="primary" {{ in_array( $category->id, $newsCategoriesId ) ? 'checked' : '' }} >
                                @endforeach
                            </div>

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/news/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if( count($news) > 0 )
            @foreach( $news as $singleNews )
                <div class="row">
                    <div class="col-sm-3">
                    <img class="img-responsive img-thumbnail" src="{{ asset('/storage/news-images') }}/{{ $singleNews->image }}" alt="">
                    </div>
                    <div class="col-sm-9">
                        <a href="/news/{{ $singleNews->id }}"><h3>{{ $singleNews->title }}</h3></a>
                        <p>{{ $singleNews->excerpt }}</p>
                        <m class="text-white bg-success">{{ $singleNews->kind == 'ویژه' ? 'ویژه' : '' }}</m>
                        @auth
                        <div class="pull-right">
                            <a href="{{ route('news.edit', [ 'id' => $singleNews->id ] ) }}" class="btn btn-primary">Edit</a>
                            <form method="post" action="{{ route('news.destroy', [ 'id' => $singleNews->id ] ) }}" style="display:inline-block">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="delete">
                                <input type="submit" class="btn btn-danger" value="delete">
                            </form>
                        </div>
                        @endauth
                    </div>
                </div><br>
            @endforeach
            <div class="row">
                {{ $news->links() }}
            </div>
        @else
            <h3>There isn't any news.</h3>
        @endif

    </div>
@endsection

resources/views/news/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
             <h1>{{ $news->title }}</h1>
        </div>
        <img class="img-thumbnail" src="{{ asset('/storage/news-images') }}/{{ $news->image }}" alt="">
        <div>
            {!! $news->body !!}
        </div>
        <br>
        <p class="text-right bg-info text-white"><strong>{{ $news->type }}</strong></p>
        <hr>
        <h3 class="text text-xl-left">Comments</h3>
        <div>
            @foreach( $comments as $comment )
                <div style="border-bottom: solid 2px #000">
                    <h3><strong>{{ $comment->name }}</strong></h3>
                    <p style="padding-left: 30px;">
                        {{ $comment->description }}
                    </p>
                    @if( !$comment->is_active )
                        <div class="pull-right">
                            <a href="{{ route('comments.approve', [ 'id' => $comment->id ]) }}" class="btn btn-success">Approve</a>
                        </div><div class="clearfix"></div>
                    @endif
                </div>
            @endforeach
        </div><br>
        <div>
            <p class="text text-center">Leave a comment</p>
            <br>
            <form method="post" action="{{ route('comments.store') }}">
                {{ csrf_field() }}
                <input type="hidden" name="news_id" value="{{ $news->id }}">
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" value="{{ old('name') }}" id="name" name="name" >
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" value="{{ old('email') }}" id="email" name="email" >
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea type="text" class="form-control" id="description" name="description" >{{ old('description') }}</textarea>
                </div>
                <div class="form-group">
                    <input class="btn btn-primary" value="Register" type="submit" class="form-control">
                </div>
            </form>
        </div>
    </div>
@endsection